---
title: "第三篇 R统计分析"
author: "beitta#微信"
date: "2014-11-30"
output:  ioslides_presentation
logo: ../pic/rlogo.png
css: ../html/0intro.css

---

## 大纲
-  **数据操作**  
-  **描述统计**    
-  **假设检验**  
-  **相关分析**  
-  **方差分析**   
-  **回归分析**   
-  **因子分析**   
-  **时间序列**   


##  数据操作
- 数据编辑  
```{r}
v0=rnorm(10);             # v1=edit(v0)
m0=sapply(c(2,2),runif)   # m1=edit(m0)
d0=data.frame(m0)         # d0[2,2]=0; d0$X1[1]=0;
```
- 自带数据  
```{r}
#data()
data(sleep);tail(sleep,2)

```

##  数据操作
- 筛选  
```{r}
v0=rnorm(10); v1=v0[v0>0.5]; v1
d0=data.frame(n=1:4,s=rep(c("aa","bb"),2),x=runif(4))
d1=d0[d0$n>2 & d0$s=="aa",]
```
- 排序  
```{r,echo=1}
v0=round(runif(n=10,min=1,max=20));               # v0[order(v0)]==sort[v0]
c(paste('v0       :',paste(v0,collapse = " ,")),  # decreasing = FALSE
  paste('sort(v0) :',paste(sort(v0),collapse = " ,")),
  paste('order(v0):',paste(order(v0),collapse = " ,"))
  )
```

##  数据操作
- 排序2  
```{r}
d0=round(sapply(rep(5,3),runif)*20);d0=data.frame(d0);
colnames(d0)=c("x","y","z");d0
ord=order(d0$x,-d0$y);      d1=d0[ord,];d1

```

##  数据操作
- 抽样  
```{r}
x=1:10;sample(x,5); # replace, prob
sample(x,20,replace=TRUE,prob=rep(c(0.2,0.8),5)) #rnorm

```

##  概率统计-不得不说
- 概率分布  
```{r}
# 样本空间/随机变量/概率分布  
par(mfrow = c(1, 3));xu=runif(100);xn=rnorm(100);xl=rlnorm(100);
hist(xu,col='blue');hist(xn,col='green');hist(xl,col='black');
```

##  概率统计-不得不说
- 概率分布  
```{r}
# 密度函数/分布函数  
par(mfrow = c(1, 2)); x=seq(-3,3,0.1);
plot(dnorm(x),type='b');plot(pnorm(x),type='b');

```

##  概率统计-不得不说
- [大数定律](http://baike.baidu.com/view/21250.htm)      
> 切比雪夫/伯努利/辛钦  
> 数学期望/标准差/方差(统计量)

- [中心极限定理](http://lxy.cumtb.edu.cn/gailvtongjidaoxue/chap5.htm)  
> 自然规律  
> 高尔顿钢板试验  
[试验](../ref/galton.exe) 

- 概率统计应用  
> 不规则面积计算    
> 仿真模拟    
> 圆周率估计  
[试验](../ref/pai.exe)  

##  描述统计
- 统计量    
```{r}
data(cars)
cars$price=round(runif(nrow(cars),min=0.8,max=10),2)
head(cars)

```

##  描述统计
- 基本统计    
```{r}
# sum , (mean,var,sd,min,max,,median,mad)
sum(cars)  #vector/list/matrix/data.frame
sum(cars$spped)  #vector/list/matrix/data.frame
# 行列统计  
apply(cars,1,sum)
apply(cars,2,sum)

```

##  描述统计
- 基本统计    
```{r}
# 非单一返回  fivenum, quantile
range(cars)
range(cars$speed)
apply(cars,2,range)

```

##  描述统计
- 分类汇总     
```{r}
dtmp=tail(cars)
x=ave(dtmp[,2],dtmp[,1],FUN=function(x) median(x))  # factor
dtmp$distgpspeed=x; dtmp

```

##  描述统计
- 分类汇总     
```{r}
dagg=aggregate(cbind(dist,price)~speed,cars,mean);head(dagg,3)
xtabs(price~speed+dist ,head(dagg))  

```

##  描述统计
- 分类汇总     
```{r}
table(tail(cars$speed))
s=cars$speed;max(s);length(s)
a=tabulate(s);length(a) # 小于等于0，忽略

```

##  描述统计
- 茎叶图       
```{r}
dt=cars$dist;dt[dt>=60&dt<80];stem(dt)

```

##  描述统计
- 基本统计量       
```{r}
summary(cars) # r object

```


##  假设检验
- 均值检验     
```{r}
# t.test(x,y=NULL,alternative=c("two.sided","less","greater"),conf.level=0.95)
data(sleep);head(sleep,1);plot(extra ~ group,sleep)
t.test(extra ~ group, data = sleep)  

```

##  假设检验
- 没有假设，就没有靠谱的检验     
```{r}
t.test(rnorm(100),rnorm(100)+1)
t.test(rnorm(100),c(rnorm(100)+1,1000)) # 尽然没差异...

```

##  假设检验
- 方差检验      
```{r}


```





##  数据操作
- 数据编辑  
```{r}

```

- 自带数据  
```{r}

```



##  参考
![1]: 毛岭峰,2011,"R语言基础"   
![2]: 徐俊晓,2012,"统计学与R读书笔记(第六版)"

